version: '3'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: '0769888'
      WORDPRESS_DB_PASSWORD: 'kefang0.---'
      WORDPRESS_DB_NAME: '0769888'
    volumes:
      - ./app/wp-content:/var/www/html/wp-content/
      - ./app/config/php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  db:
    image: mysql:5.7
    restart: always
    ports:
     - 3366:3306
    environment:
      MYSQL_DATABASE: '0769888'
      MYSQL_USER: '0769888'
      MYSQL_PASSWORD: 'kefang0.---'
      MYSQL_ROOT_PASSWORD: 'SlCUeVxNVbNpu9eESC3b14d'
    volumes:
      - ./app/db:/var/lib/mysql
